### PR TITLE
PR #70 for v1.6

### PR DESCRIPTION
**Pull request by ankit61d**
Implementing the PR #70 solution for v1.6 issues

### CODE REVIEW

**Comment by thisisayush** [comment]
Hi,
This will require an upgrade script similar to https://github.com/blockonomics/prestashop-plugin/pull/70/files#diff-8ce2d50588a16d29008fbabecc44509eed7221de834477662e903e8e64f0e433 to allow upgrade from previous release as we have added a new column.

**Comment by ankit61d** [comment]
DB upgrade script to add new column `id_order` in blockonomics table: https://github.com/blockonomics/prestashop-plugin/pull/156/commits/a630b0bfeade1048c55c633dc05f4b54475ac6c4

Upgrading module screenshot:
chrome_f3DVqXQ97Z

------

Note: Currently there are 2 issues with Test Setup. When Test Setup button is hit:

1. If no callback URL is set, update callback on server 
2. If only secret differs, update callback on server

These are not addressed in this PR and will be addressed in a separate PR.

**Comment by thisisayush** [comment]
Tested and Working including Fresh Install and Upgrade!

**Comment by shivaenigma** [comment]
Let us remove the upgrade script. We stopped supporting 1.6 a while ago and don't know what state their module is in. Better to install on a fresh install

**Pull request merged**
